import React from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useMutation } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { toast } from "@/hooks/use-toast";
import { Loader2, FileText } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

// Define the form schema with zod
const formSchema = z.object({
  theme: z.string().min(3, { message: "Theme must be at least 3 characters" }),
  ageGroup: z.string().min(1, { message: "Please select an age group" }),
  additionalNotes: z.string().optional(),
});

type FormValues = z.infer<typeof formSchema>;

export default function LessonPlanMaker() {
  const [lessonPlanContent, setLessonPlanContent] = React.useState<string | null>(null);
  const [citations, setCitations] = React.useState<string[]>([]);
  
  // Setup form with react-hook-form and zod validation
  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      theme: "",
      ageGroup: "",
      additionalNotes: "",
    },
  });
  
  // Setup mutation for API call
  const mutation = useMutation({
    mutationFn: (data: FormValues) => {
      return apiRequest("/api/lesson-plan", {
        method: "POST",
        data,
      });
    },
    onSuccess: (data) => {
      setLessonPlanContent(data.lessonPlan);
      setCitations(data.citations || []);
      toast({
        title: "Lesson Plan Created",
        description: "Your lesson plan has been generated successfully!",
        variant: "default",
      });
    },
    onError: (error) => {
      console.error("Error generating lesson plan:", error);
      toast({
        title: "Error",
        description: "Failed to generate lesson plan. Please try again.",
        variant: "destructive",
      });
    },
  });
  
  // Handle form submission
  const onSubmit = (data: FormValues) => {
    mutation.mutate(data);
  };
  
  // Print lesson plan
  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Lesson Plan - ${form.getValues().theme}</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; }
              h1 { color: #1a1a1a; text-align: center; }
              .header { margin-bottom: 20px; }
              .logo { text-align: center; font-size: 24px; font-weight: bold; color: #7c3aed; }
              .footer { margin-top: 20px; font-size: 12px; text-align: center; color: #666; }
            </style>
          </head>
          <body>
            <div class="header">
              <div class="logo">Raising Arizona Preschool</div>
              <h1>Lesson Plan: ${form.getValues().theme}</h1>
              <p><strong>Age Group:</strong> ${form.getValues().ageGroup}</p>
            </div>
            ${lessonPlanContent}
            <div class="footer">
              <p>Generated by MentorMe - Raising Arizona's Teacher Training Platform</p>
              ${citations.length > 0 ? '<h3>References</h3><ul>' + citations.map(cite => `<li>${cite}</li>`).join('') + '</ul>' : ''}
            </div>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto">
      <Card className="mb-8">
        <CardHeader>
          <CardTitle className="text-2xl font-bold">Weekly Lesson Plan Maker</CardTitle>
          <CardDescription>
            Create a comprehensive, age-appropriate weekly lesson plan based on your chosen theme
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <FormField
                  control={form.control}
                  name="theme"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Theme</FormLabel>
                      <FormControl>
                        <Input placeholder="e.g. Ocean Animals, Space Exploration, Seasons" {...field} />
                      </FormControl>
                      <FormDescription>
                        Enter the main theme for your weekly activities
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                
                <FormField
                  control={form.control}
                  name="ageGroup"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Age Group</FormLabel>
                      <Select 
                        onValueChange={field.onChange} 
                        defaultValue={field.value}
                      >
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select an age group" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="Infants (0-12 months)">Infants (0-12 months)</SelectItem>
                          <SelectItem value="Toddlers (1-2 years)">Toddlers (1-2 years)</SelectItem>
                          <SelectItem value="Early Preschool (2-3 years)">Early Preschool (2-3 years)</SelectItem>
                          <SelectItem value="Preschool (3-4 years)">Preschool (3-4 years)</SelectItem>
                          <SelectItem value="Pre-K (4-5 years)">Pre-K (4-5 years)</SelectItem>
                          <SelectItem value="School Age (5-12 years)">School Age (5-12 years)</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormDescription>
                        Select the age group for your classroom
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
              
              <FormField
                control={form.control}
                name="additionalNotes"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Additional Notes</FormLabel>
                    <FormControl>
                      <Textarea 
                        placeholder="Add any special considerations, learning goals, or requests for your lesson plan" 
                        className="min-h-[120px]" 
                        {...field} 
                      />
                    </FormControl>
                    <FormDescription>
                      Include any specific activities, skills, or concepts you want covered (optional)
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
              
              <Button 
                type="submit" 
                className="w-full" 
                disabled={mutation.isPending}
              >
                {mutation.isPending ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Creating Lesson Plan...
                  </>
                ) : (
                  "Generate Lesson Plan"
                )}
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>
      
      {lessonPlanContent && (
        <Card className="mb-8">
          <CardHeader className="flex flex-row items-center justify-between">
            <div>
              <CardTitle>Your Lesson Plan</CardTitle>
              <CardDescription>
                Theme: {form.getValues().theme} | Age Group: {form.getValues().ageGroup}
              </CardDescription>
            </div>
            <Button onClick={handlePrint} className="flex items-center gap-2">
              <FileText className="h-4 w-4" />
              Print/Save
            </Button>
          </CardHeader>
          <CardContent>
            <div 
              className="prose prose-indigo max-w-none" 
              dangerouslySetInnerHTML={{ __html: lessonPlanContent }}
            />
            
            {citations.length > 0 && (
              <div className="mt-8 border-t pt-4">
                <h3 className="text-lg font-medium mb-2">References</h3>
                <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
                  {citations.map((citation, i) => (
                    <li key={i}>
                      <a href={citation} target="_blank" rel="noopener noreferrer" className="hover:underline">
                        {citation}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}